apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-uygulamasi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web-uygulamasi
        image: mutlueda/web-uygulamasi:v1
        ports:
        - containerPort: 80
